name = "nuxust"
pages_build_output_dir = "dist"
compatibility_date = "2025-04-02"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "0ca10b628ab044aab34dfbca835b3ed0"

